server:
  port: 8080
spring:
  application:
    name: help-center-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

