server:
  port: 8080
spring:
  application:
    name: help-center-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      httpclient:
        websocket:
          max-frame-payload-length: 20000000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
chat:
  timeout: 4
#logging:
#  level:
#    root: debug