server:
  port: 8080
spring:
  application:
    name: help-center-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://help-center-auth
          predicates:
            - Path=/api/v1/auth/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

